# This is a test workflow for Pharos. It runs on push events to the trivy-with-vex branch and executes the Pharos action with specified parameters.
name: Test Pharos
on:
  push:
    branches:
      - trivy-with-vex
jobs:
  test-pharos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Pharos
        uses: ./
        with:
          image_url: python:3.4-alpine 
          trivy_vex: true